const $=s=>document.querySelector(s),map=L.map('map').setView([35.1796,129.0756],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let pos=null,userMarker=null,selected=null,radius=3,routeMode='walk',expanded=false,allResults=[],markers=L.layerGroup().addTo(map),circle=null;
const fmt=km=>km<1?`${Math.round(km*1000)}m`:`${km.toFixed(1)}km`,distance=p=>map.distance([pos?.lat??35.1796,pos?.lng??129.0756],[p.lat,p.lng])/1000,escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markerIcon(p){const emoji=(p.category||'').includes('카페')?'☕':'📍';return L.divIcon({className:'',html:`<div class="facility"><span>${emoji}</span></div>`,iconSize:[34,34],iconAnchor:[17,34]})}
function showStatus(message,ok=false){$('#status').textContent=message;$('#status').className=`status${ok?' ok':''}`}
function drawRadius(){if(circle)map.removeLayer(circle);const origin=pos||{lat:35.1796,lng:129.0756};circle=L.circle([origin.lat,origin.lng],{radius:radius*1000,color:'#1769e0',weight:2,fillColor:'#1769e0',fillOpacity:.05,interactive:false}).addTo(map);$('#mapNote').textContent=`파란 원은 ${radius}km 검색 범위입니다`;}
function choose(p,focus=true){selected=p;const km=distance(p),mins=Math.max(1,Math.round(km*12));$('#info').innerHTML=`<small>카카오 제공 장소 정보</small><h2>📍 ${escape(p.name)}</h2><p>${escape(p.address)}</p><p><b>${fmt(km)} · 도보 약 ${mins}분</b></p>`;$('#routeTitle').textContent=p.name;$('#routeText').textContent=`${pos?'내 위치':'부산 중심'}에서 ${fmt(km)} · ${routeMode==='walk'?'도보':routeMode==='traffic'?'대중교통':'자동차'} 경로를 확인합니다.`;if(focus)map.setView([p.lat,p.lng],17)}
function renderResults(){markers.clearLayers();const shown=expanded?allResults:allResults.slice(0,4);$('#results').classList.toggle('expanded',expanded);$('#results').innerHTML=shown.length?shown.map((p,i)=>`<li><button data-i="${i}"><b>📍 ${escape(p.name)}</b><b>${fmt(distance(p))}</b><small>${escape(p.category||'장소')} · ${escape(p.address)}</small></button></li>`).join(''):'<li>검색 결과가 없습니다.</li>';allResults.forEach(p=>L.marker([p.lat,p.lng],{icon:markerIcon(p)}).addTo(markers).bindTooltip(p.name,{direction:'top'}).on('click',()=>choose(p,false)));document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const p=shown[Number(b.dataset.i)];choose(p);});$('#more').hidden=allResults.length<=4;$('#more').textContent=expanded?'접기':`더보기 (${allResults.length-4}곳)`}
async function search(){const query=$('#search').value.trim();if(!query)return showStatus('장소 또는 시설명을 입력해 주세요.');showStatus(`카카오에서 ${radius}km 반경 전체를 검색하고 있어요…`);drawRadius();try{const origin=pos||{lat:35.1796,lng:129.0756},params=new URLSearchParams({query,x:origin.lng,y:origin.lat,radius:String(radius*1000)}),res=await fetch(`/api/place-search?${params}`),data=await res.json();if(!res.ok)throw new Error(data.error||'카카오 장소 검색에 실패했습니다.');allResults=(data.documents||[]).map(d=>({name:d.place_name,address:d.road_address_name||d.address_name||'주소 정보 없음',category:d.category_name,lat:Number(d.y),lng:Number(d.x),phone:d.phone})).filter(p=>Number.isFinite(p.lat)&&distance(p)<=radius).sort((a,b)=>distance(a)-distance(b));expanded=false;renderResults();if(allResults[0])choose(allResults[0],false);showStatus(`${pos?'내 위치':'부산 중심'} ${radius}km 안의 카카오 장소 ${allResults.length}곳을 표시했습니다.`,true)}catch(e){showStatus(e.message)}}
$('#searchForm').onsubmit=e=>{e.preventDefault();search()};$('#more').onclick=()=>{expanded=!expanded;renderResults()};
$('#locate').onclick=()=>{if(!navigator.geolocation)return showStatus('이 브라우저는 위치 기능을 지원하지 않습니다.');showStatus('위치 권한을 요청하고 있어요…');navigator.geolocation.getCurrentPosition(p=>{pos={lat:p.coords.latitude,lng:p.coords.longitude};if(userMarker)userMarker.setLatLng([pos.lat,pos.lng]);else userMarker=L.marker([pos.lat,pos.lng],{icon:L.divIcon({className:'',html:'<div class="user"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map);map.setView([pos.lat,pos.lng],15);drawRadius();showStatus(`● 현재 위치 확인됨 · 정확도 약 ${Math.round(p.coords.accuracy)}m`,true)},()=>showStatus('위치 권한을 허용해 주세요. 주소 표시줄의 위치 권한을 확인하세요.'),{enableHighAccuracy:true,timeout:15000})};
[1,2,3,4,5].forEach(km=>{const b=document.createElement('button');b.textContent=`${km}km 이내`;b.className=km===radius?'active':'';b.onclick=()=>{radius=km;document.querySelectorAll('#radiusButtons button').forEach(x=>x.classList.toggle('active',x===b));drawRadius();if($('#search').value.trim())search()};$('#radiusButtons').appendChild(b)});drawRadius();
document.querySelectorAll('#modes button').forEach(b=>b.onclick=()=>{routeMode=b.dataset.mode;document.querySelectorAll('#modes button').forEach(x=>x.classList.toggle('active',x===b));$('#routeButton').textContent=`카카오맵에서 ${{walk:'도보',traffic:'대중교통',car:'자동차'}[routeMode]} 길찾기`;if(selected)choose(selected,false)});
$('#routeButton').onclick=()=>{if(!selected)return $('#routeText').textContent='먼저 장소를 검색하고 핀을 선택해 주세요.';if(!pos)return $('#routeText').textContent='내 위치 정보 찾기 후 길찾기를 이용해 주세요.';const start=`${encodeURIComponent('내 위치')},${pos.lat},${pos.lng}`,end=`${encodeURIComponent(selected.name)},${selected.lat},${selected.lng}`;window.open(`https://map.kakao.com/link/by/${routeMode}/${start}/${end}`,'_blank','noopener');};
